exclude all sub-pages of user-pages from "new community members"
indieweb/this-week pull request #5
Opened 2017-06-13 19:30 UTC by sknebel

Fix for #4 – this seemed easy enough even for my nearly non-existent level of PHP skills ;)

2017-06-14 07:46 UTC, strugee requested changes
@sknebel I'm not a committer for this repo but I saw your PR pop up in my notifications and thought I'd take a look - hope you don't mind :)

You might also want to adjust your commit message so it's [capitalized](https://chris.beams.io/posts/git-commit/#capitalize) and so the body includes "Fixes #4" (so issue #4 autocloses).

2017-06-14 07:46 UTC, strugee commented on generate-wiki-summary.php
> +			//subpages of user-pages are excluded (e.g. user css or personal test pages)
Probably want `// Subpages` instead of `//subpages`, for consistency with other comments

2017-06-14 07:46 UTC, strugee commented on generate-wiki-summary.php
> +			//subpages of user-pages are excluded (e.g. user css or personal test pages)
Also CSS is all-caps

2017-06-14 07:46 UTC, strugee commented on generate-wiki-summary.php
> -			if(preg_match('/^user:/i', $title) && !preg_match('/\.css$/i', $title))
The regex for `.css` seems to have disappeared here; what happened to it?

2017-06-22 08:07 UTC, sknebel commented on generate-wiki-summary.php
> -			if(preg_match('/^user:/i', $title) && !preg_match('/\.css$/i', $title))
custom CSS is just a specific type of subpage

2017-06-23 20:36 UTC, merged